### ISSUE TITLE
protofire audit EGD13-02 Lack of Non-Zero Validation for Constructor Parameters

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#182]
The FtsoV2LTSFeedOracle contract's constructor does not validate that the feedId and staleAfter parameters are non-zero. This can lead to incorrect contract initialization if invalid parameters are provided, potentially causing the contract to behave unexpectedly or fail to function as intended.

**Comment by thedavidmeister** [comment]
1. feed ID

For all I know, `0` might be a valid feed ID in the future, this is set by Flare and outside my control/knowledge for the future.

2. staleAfter

A `0` value is also valid for flare ftsos as they have realtime feeds per-block, so setting this to `0` would ensure that only values that are fresh as of the block the transaction is in are allowed to be used.

**Comment by BlackienBad** [comment]
agreed
