### ISSUE TITLE
protofire audit EGD13-03 Incomplete Documentation References

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#183]
The ReceiptVault contract contains several references to the @inheritdoc IReceiptVaultV1 tag in its documentation comments. However, these references lead to non-complete documentation, which can cause confusion and misinterpretation for developers and auditors trying to understand the contract's functionality and intended behavior.

**Comment by thedavidmeister** [comment]
docs updated here https://github.com/gildlab/ethgild/pull/195

**Comment by BlackienBad** [comment]
Will mark as fixed in the report
