### ISSUE TITLE
protofire audit EGD13-04 Public Functions Can Be Declared External

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#184]
In the ReceiptVault contract, some functions such as maxWithdraw(), previewWithdraw(), and withdraw() are declared as public. However, these functions do not need to be called internally within the contract and can be declared as external to save gas. Declaring functions as external instead of public can reduce gas costs because external functions are more efficient in terms of gas usage when called from outside the contract.

**Comment by thedavidmeister** [comment]
i just made everything that was public into `external` and `override` as the `ReceiptVault` is abstract

https://github.com/gildlab/ethgild/pull/197/files

**Comment by thedavidmeister** [comment]
updating cyclo to use latest https://github.com/cyclofinance/cyclo.sol/pull/2

i couldn't convert the `uri` function because the base implementation from OZ uses public

**Comment by BlackienBad** [comment]
Agreed, will be solved in the report
