### ISSUE TITLE
protofire audit sol version

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#185]
The Solidity pragma version 0.8.25 is used. This version introduces the PUSH0 opcode, which may not be supported by all EVM-compatible chains. The PUSH0 opcode was introduced in Solidity version 0.8.20.

**Comment by thedavidmeister** [comment]
We can use solidity version 0.8.25 and target `paris` which is the latest fork that does not use `PUSH0` or newer opcodes

**Comment by thedavidmeister** [comment]
https://github.com/gildlab/ethgild/pull/186 adds `paris` to this repo so that all tests run against it, and any deployments from this repo will use it

**Comment by thedavidmeister** [comment]
https://github.com/cyclofinance/cyclo.sol/pull/1 adds `paris` to cyclo repo and updates this repo as a dependency, so the cyclo deployments will use it

**Comment by BlackienBad** [comment]
Confirmed

**Comment by BlackienBad** [comment]
But is it only in cyclo? its not used in the ethgild repo?

**Comment by thedavidmeister** [comment]
@BlackienBad i added `paris` to the foundry toml in both repos

**Comment by BlackienBad** [comment]
perfect
