### ISSUE TITLE
protofire audit unstructured event data

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#187]
The receiptInformation() function in the Receipt contract can be invoked at any time by any user. However, there is no specific event type associated with this function. This can lead to potential confusion when reading and interpreting events, as it may not be clear which function invocation triggered a particular event.

**Comment by BlackienBad** [comment]
This is intended mainly as a risk, it is not intended as a vulnerability, so it will stay in the report, but it's important that the team is aware of this

**Comment by thedavidmeister** [comment]
@BlackienBad yes we are aware, it is by design, which is why we implement self describing metadata everywhere
