### ISSUE TITLE
protofire hardcoded feed ids

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#189]
The LibFtsoV2LTS library contains hardcoded feed IDs for various cryptocurrency/USD pairs. While these addresses are assumed to be correct, they may need to be updated if the project is deployed on another blockchain or if the feed addresses change. Relying on hardcoded addresses can lead to issues if the addresses are incorrect or need to be modified, as it requires changes to the source code and redeployment of the contract.

**Comment by thedavidmeister** [comment]
The V2 LTS FTSOs are LTS, i.e. "long term stable". If they change the feeds then the stability guarantee is broken, it's correct to treat these as immutable values, as the cysFLR contract itself is also immutable.

If the feed address is incorrect then we would see that as either an error (most likely), or incorrect prices (probably very obvious).

Hardcoding these values is intended to reduce the risk of human error (e.g. like putting variables in the environment on github, or manually entering them) as they gain test coverage and git history auditability/accountability/management.

FTSOs are specific to Flare so there aren't really any other chains to deploy to, but if there was, yes we'd have to add new feed IDs relevant to the new chain/requirements. This is a pretty trivial task, so it isn't a problem and won't impact any already deployed contracts.

**Comment by BlackienBad** [comment]
This is intended mainly as a risk, it is not intended as a vulnerability, so it will stay in the report, but it's important that the team is aware of this

**Comment by thedavidmeister** [comment]
ok, but also @BlackienBad FYI that the feed IDs are not addresses, they're internal IDs specific to the flare FTSO system.

we don't hardcode addresses for contracts, we pull them from the relevant registries, but once we get to an LTS V2 FTSO the feed IDs are all just arbitrary identifiers specific to their system

the original wording of the risk references "feed ID" and "address" interchangeably, but they are not, which makes me think perhaps you've misunderstood the FTSO system slightly.

e.g. the registry lookup is here https://github.com/rainlanguage/rain.flare/blob/main/src/lib/lts/LibFtsoV2LTS.sol#L79

the "get feed" call that uses a feed ID is here https://github.com/rainlanguage/rain.flare/blob/main/src/lib/lts/LibFtsoV2LTS.sol#L91 but it isn't getting a feed address/contract, it is getting a feed _value_ from the registry that we previously looked up

**Comment by BlackienBad** [comment]
This is basically to say that we did look at the code and if the addresses hardcoded are right there is no problem, we do not look at the address on-chain to check that it refers to the right contract
The feed id and address are not used interchangeably but using the word address instead of feed id would make the phrase less clear for whoever is reading it
