### ISSUE TITLE
For OffchainAssetVault, add a new event for each deposit/withdraw that includes the info in Deposit/Withdraw event + the receipt info + the receipt id

### ISSUE THREAD

**Issue by hardyjosh** [gildlab/ethgild#19]
The subgraph is unable to link events emitted as a result of the same `deposit` or `withdraw`.

The Deposit has information on the sender and the # of shares minted, but there's no way to know the associated ReceiptInformation and TransferSingle (includes the 1155 id) events.

You could say "consider all events emitted in the same transaction to be linked", but consider the edge case where a wrapping contract could call deposit twice in the same transaction.

**Comment by thedavidmeister** [comment]
this was done with `DepositWithReceipt` and `WithdrawWithReceipt` but withdraw only has receipt id there's no additional information on the asset being burned
