### ISSUE TITLE
protofire snapshot useage 

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#190]
The ReceiptVault contract uses the ERC20SnapshotUpgradeable contract from OpenZeppelin, which has been removed in version 5.0.0 of OpenZeppelin's contracts. Although it appears that the contract was not removed due to security vulnerabilities, it is an older library that may carry inherent risks associated with deprecated software. The team has specified that this contract is used for off-chain components, which are not covered in this audit.

**Comment by thedavidmeister** [comment]
yup, this is out of scope because i'm fairly sure there's no code paths in cyclo that hit this from any externally callable code, and therefore the compiler should be removing it all from the compiled artifacts anyway

worst case, we have to pay a bit more gas to deploy due to some unreacheable cruft in the evm bytecode, but i don't think that's happening

ReceiptVault is a shared abstract contract so it has affordances for snapshotting, but the concrete implementations don't need to use/implement them.

I'm not aware of any problems with the snapshotting logic in 4.x i _assume_ probably OZ just removed it to reduce their own scope as it has relatively niche utility from their perspective due to the gas concerns, and isn't based on any ERC standard.

**Comment by BlackienBad** [comment]
This is intended mainly as a risk, it is not intended as a vulnerability, so it will stay in the report, but it's important that the team is aware of this

**Comment by thedavidmeister** [comment]
@BlackienBad to be clear, the compiler removes this code from Cyclo, so it's not even a risk because it only exists in the abstract class, not the concrete contract that gets deployed, unless we can show that the compiler does in fact keep the code paths in the final artefacts and they are somehow reachable from an external call

i'm not sure that i said the code was used by "offchain components", if i did, then it was a typo

it's used by _offchain asset vault_ https://github.com/gildlab/ethgild/blob/main/src/concrete/vault/OffchainAssetReceiptVault.sol

which is a different concrete contract, not part of Cyclo and for an entirely different use case (RWA), and so out of scope, but the snapshotting there is entirely onchain

there's an external code path that reaches the snapshot logic in that contract https://github.com/gildlab/ethgild/blob/main/src/concrete/vault/OffchainAssetReceiptVault.sol#L430 so in that case, this risk would apply to that contract

but it's a different concrete contract that has nothing to do with Cyclo, so i'm not sure how this risk applies to Cyclo?

**Comment by BlackienBad** [comment]
Understood, it can be removed from the report
