### ISSUE TITLE
protofire immutable values in proxies

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#191]
In a few upgradeable contracts, the constructor is used to initialize immutable variables. Since the value of immutable variables is stored in the bytecode, it will be shared among all proxies pointing to a given contract instead of being stored in each proxy’s storage.

**Comment by thedavidmeister** [comment]
yes, the immutable values for ReceiptVault are intentional, because they're essentially extensions of the core logic and so shouldn't be modifiable across all proxies, the storage variables are named `s*` and are useful to change per-proxy, because you would want different assets to deposit and the receipt contract needs to be created and owned by the proxy.

the oracles are not intended for cloning and so aren't designed to be proxied, because they are stateless so any given configuration only ever needs to be deployed once, so the gas optimisation is for use not deployment (proxies cost more to call)

i don't think there are any other contracts where this is relevant, but correct me if i'm wrong?

**Comment by BlackienBad** [comment]
This is intended mainly as a risk, it is not intended as a vulnerability, so it will stay in the report, but it's important that the team is aware of this

**Comment by thedavidmeister** [comment]
@BlackienBad ok yes, assuming i haven't made any mistakes, the mix of immutable and in-store variables is intentional as both have tradeoffs, such as gas and proxy behaviours etc.

i've tried to optimise each on a case by case basis, rather than say "everything is immutable" or "everything is in storage"

if you see a specific example that looks suspicious then please flag it, but otherwise i think this is fine and by design
