### ISSUE TITLE
protofire token decimals

### ISSUE THREAD

**Issue by thedavidmeister** [gildlab/ethgild#193]
Most calculations in the project assume that tokens have 18 decimals. While this is a common standard, it is not universally true. Tokens with different decimal places may lead to incorrect calculations and potential vulnerabilities.

**Comment by thedavidmeister** [comment]
using 18 decimal fixed point math to represent ratios of numbers is not the same thing as assuming something about the behaviour of token values.

erc20 specification states not to assume that the decimals even exist for a token https://eips.ethereum.org/EIPS/eip-20#decimals because decimals are for the user representation

```
Returns the number of decimals the token uses - e.g. 8, means to divide the token amount by 100000000 to get its user representation.

OPTIONAL - This method can be used to improve usability, but interfaces and other contracts MUST NOT expect these values to be present.
```

as explained in https://github.com/gildlab/ethgild/issues/181 the oracle interface that has been defined and implemented in this repo mandates 18 decimals for everything, so any scaling for values that are supposed to be decimal values coming from an oracle need to be rescaled within the oracles upstream.

this is already part of the V2 FTSO LTS contract, they are normalized to 18 decimals, the V1 of FTSO oracles did not rescale upstream for example, and there used to be rescaling logic to handle that in the older oracles.

the only place that Cyclo uses fixed point math is to handle the share ratio, which is a unitless conversion between assets and shares, represented as 18 decimal math.

If there was an economic discrepancy between asset/share due to their decimals, the share ratio oracle would need to be scaled appropriately, but I don't think anything else would change, because all other mul/div operations are just based on snapshots of the original oracle ratios inverted (e.g. when withdrawing based on price/id)

**Comment by BlackienBad** [comment]
As said earlier, the risks are not vulnerabilities, but merely observations that are made present in the report
They often are design choices, but as the name suggests, they are risks and not vulnerabilities

**Comment by thedavidmeister** [comment]
@BlackienBad sure, i understand it's just presented as an FYI, but i'm also explaining that even if the tokens had a decimal mismatch, that probably wouldn't change the contract logic, it would only mean the oracle ratios need to scale appropriately

having the conversation here in github means that if the general public is curious they can get the full context
